httpListener:
  port: "8091"
  
anypointplatform:
  host: "anypoint.mulesoft.com"
  csorgpath: "/accounts/api/cs/organizations/"
  environments: "/environments?&limit=200"
  armuiapplications: "/armui/api/v1/applications"
  ch1applications: "/cloudhub/api/organizations/"
  exchangebasepath: "exchange/api/v2/assets/"
  ch2applications: "/amc/application-manager/api/v2/organizations/"
  hybridapplications: "/hybrid/api/v1/applications/"
  filterEnvironments: "false"
  environmentsToBeProcessed: ""

filePathOnDisk:
  separator: "/"
  outputOrgDirectory: "/tmp/"
  outputJarSrcDirectory: "/source/jar/"
  outputClsLdrSrcDirectory: "/source/class/"
  outputCSVFileExtension: ".csv"

cacheSettings:
  maxEntries: "1000"
  entryTtl: "600"
  expirationInterval: "300"
  
extensionsProvidedByMulesoft:
  types: "mule-client-id-enforcement-extension,mule-cors-extension,mule-event-authentication-extension,mule-federation-extension,mule-http-policy-transform-extension,mule-http-proxy-extension,mule-ip-filter-extension,mule-json-threat-protection-extension,mule-jwt-extension,mule-rest-validator-extension,mule-soap-fault,mule-throttling-extension,mule-tokenization-extension,mule-wsdl-functions-extension,mule-xml-threat-protection-extension"
